### ISSUE TITLE
[Suggestion] Droptransfer CrossWorld Grouping

### ISSUE THREAD

**Issue by bmlzootown** [megoesrawr/Modern-LWC#96]
**Short five word summary of suggestion:** 
Add ability to specify specific worlds for droptransfer's crossWorld feature.

**Detailed description of suggestion:**
LWC has had droptransfer for a while now, as well as the ability to use said feature across different worlds, but I'd like to take that a step further. My request is to add a config option(s) to group/link specific worlds together rather than just limiting permissions to specific worlds, as that would limit usage to one group of worlds. Below is an example, for clarification:
```yaml
# Example
modes:
    droptransfer:
        enabled: true

        # allow items to be transferred across world boundaries
        crossWorld:
            enabled: true

            # Example of grouped/linked worlds
            survival:
            - Survival
            - Survival_the_end
            - Survival_nether

            build:
            - Build
            - Build_nether
            - Build_the_end
            - Flatlands
```
