### ISSUE TITLE
PlayerInteractEvent causing EXTREME lag

### ISSUE THREAD

**Issue by MetalGearDaner** [megoesrawr/Modern-LWC#99]
**LWC Version (/lwc admin version):** 2.0.7 (Latest Spigot site's version)
**Server version (/version):** Paper version git-Paper-1415 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Short five word summary of issue:** PlayerInteractEvent is consuming an excessive ammount of lag.

**Detailed description of problem:**

When a player starts creating protections or managing them, the LWC plugin consumes too much resources. Here's the Aikar's Timings report:
https://timings.aikar.co/?id=edda4d88cb7f44aca67389f687bf0ea2
You can see a spike of FPS losses arround 17:17.

I've uploaded my LWC configuration file and the LWC SQLITE database as well:
https://gist.github.com/MetalGearDaner/dfe7ac588fcd8275ef44f291d5236165
https://drive.google.com/file/d/1B-oqVl2Js84tlMb7CBIUmtREkfuk3s1n/view?usp=sharing

**Comment by megoesrawr** [comment]
I suggest using MySQL for now. Sqlite is kinda buggy. This should fix that issue.

**Comment by megoesrawr** [comment]
Leave path as is.

**Comment by Tsuser1** [comment]
Here's how I have mine configured, works extremely well. Credentials are removed for obvious reasons.

```
database:
    adapter: mysql
    path: plugins/LWC/lwc.db
    host: 127.0.0.1
    database: minecraft
    username: <redacted>
    password: <redacted>
    prefix: lwc_
    ping_interval: 300
```
